site_name: CerradoTech
repo_url: https://github.com/mdsreq-fga-unb/2024.2-T03-CerradoTech

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.integrate

  palette:
    # Dark Theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Trocar para tema claro

    # Light Theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Trocar para tema escuro

nav:
  - Home: index.md
  - Visão do Produto e Projeto:
      - Cenário Atual do Cliente e Negócio: sections/cenarioAtual.md
      - Solução Proposta: sections/solucaoProposta.md
      - Estratégias de Engenharia de Software: sections/estrategia.md
      - Engenharia de Requisitos: sections/engenharia.md
      - Cronograma e Entregas: sections/cronograma.md
      - Interação entre Equipe e Cliente: sections/equipe.md
      - Referências Bibliográficas: sections/bibliografia.md
  - Backlog: 
      - Requisitos de Software: sections/requisitos.md
      - Backlog do Produto: sections/backlog.md
      - DoR e DoD: sections/dor-dod.md
  - Entregas e Lições Aprendidas:
      - Unidade 1: sections/entregaU1.md
      - Unidade 2: sections/entregaU2.md
  - Estudos de Caso:
      - PBB: sections/PBB.md
      - USM: sections/USM.md
      
