site_name: CerradoTech
repo_url: https://github.com/mdsreq-fga-unb/2024.2-T03-CerradoTech

theme:
  name: material
  language: pt-BR

  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    #Dark Theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Trocar para tema claro

    #light Theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Trocar para tema escuro

nav:
  - Home: index.md
  - Visão do Produto e Projeto:
      - Cenário Atual do Cliente e Negócio: sections/1-cenarioAtual.md
      - Solução Proposta: sections/2-solucaoProposta.md
      - Estratégias de Engenharia de Software: sections/3-estrategia.md
      - Cronograma e Entregas: sections/4-cronograma.md
      - Interação entre Equipe e Cliente: sections/5-equipe.md
      - Lições Aprendidas: sections/6-aprendizados.md
      - Referências Bibliográficas: sections/7-bibliografia.md
  - Entregas: 
      - Unidade 1: sections/entregas.md
