/* eslint-disable max-len */
/* eslint-disable quote-props */
/* eslint-disable @typescript-eslint/naming-convention */
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})

export class SocioprodutivoContent {
    readonly versao = '1.0';

    readonly grauParentesco = ['Pai', 'Mãe', 'Filho(a)', 'Tio(a)', 'Irmão(ã)', 'Outro'];

    readonly escolaridade = ['Sem instrução', 'Ensino fundamental completo', 'Ensino fundamental incompleto', 'Ensino médio incompleto', 'Ensino médio completo', 'Superior incompleto', 'Superior completo', 'N/I'];

    readonly atividadesProdutivas = [
        {value:'pecuária (gado corte ou leite)', isChecked: false },
        {value:'produção vegetal, horticultura irrigada, irrigação', isChecked: false },
        {value:'apicultura (extração de mel, própolis pólen, cera etc.)', isChecked: false },
        {value:'caprinos, ovinos, suinos', isChecked: false },
        {value:'aves caipiras e ovos', isChecked: false },
        {value:'pesca e produção de pescado', isChecked: false },
        {value:'extrativismo (baru, pequi, etc)', isChecked: false },
        {value:'beneficiamento de produtos animais', isChecked: false },
        {value:'beneficiamento de produtos vegetais', isChecked: false },
        {value:'artesanato e outras atividades não agrícolas (costura, bordado, madeira, barro, couro, palha etc.)', isChecked: false },
        {value:'outras atividades (agrícolas e não agrícolas)', isChecked: false },
    ];

    readonly tipoDap = [
        'Principal',
        'Assessória Mulher',
        'Assessória Jovem',
        'Especial',
    ];

    readonly beneficios = [
        'Aposentadoria, Previdência social',
        'Seguro desemprego',
        'Bolsa família, bolsa escola, cartão alimentação, auxílio gás, cesta básica',
        'Bolsa de educação, Educa mais Brasil, Inglês sem fronteiras',
        'Jovem aprendiz, Pronatec, Sisutec, Sisu, Prouni, FIES Pós-graduação',
        'Passe livre, cartão do idoso, CNH Social',
        'Viver sem limites, Saúde não tem preço, Rede cegonha',
        'Tarifa social de energia elétrica',
        'Minha casa minha vida, Minha casa melhor',
        'Luz no campo',
        'Luz para todos',
        'Cisterna para consumo humano - 1ª água',
        'Cisterna para produção humano - 2ª água',
        'Assistência técnica e extensão rural (ATER)',
        'Financiamento agrícola',
        'Pronaf',
        'PAA',
        'PNAE',
        'Garantia Safra',
        'Plano Brasil sem Miséria (PBSM)',
        'Seguro rural',
        'Seguro da Agricultura Familiar – SEAF (antigo Proagro)',
        'Programa de reforma agrária, crédito fundiário',
        'Programa de combate à pobreza rural',
        'Microempreendedor individual (MEI), Refis ou Programa SEBRAE',
        'Auxílios emergenciais em calamidades – Bolsa Estiagem',
        'Programa de Saúde da Família (PSF)',
        'Seguro Defeso',
        'Sistema de Abastecimento de Água pelo Estado',
        'Água para Consumo Humano em Carro-Pipa',
        'Outro programa/benefício',
    ];

    readonly servicosPublicos = [
        'Agente de saúde',
        'PSF/presença de médico na comunidade/ distrito',
        'Transporte escolar',
        'Transporte público',
    ];

    readonly destinoAtualComercializacao = [
        'PAA/PNAE',
        'Cooperativa/associação',
        'Eventos da agricultura familiar / feiras agroecológicas e orgânicas',
        'Venda para atravessador',
        'Pequenos comércios locais (ex.: feiras livres)',
        'Outros',
    ];

    readonly producaoAnimal = [
        { codigo: '101', tipo: 'Bovinos', unidade: ['cabeça', 'kg', 'arroba'] },
        { codigo: '102', tipo: 'Suínos', unidade: ['cabeça', 'kg'] },
        { codigo: '103', tipo: 'Caprinos', unidade: ['cabeça', 'kg'] },
        { codigo: '104', tipo: 'Ovinos', unidade: ['cabeça', 'kg'] },
        { codigo: '105', tipo: 'Aves', unidade: ['cabeça', 'kg'] },
        { codigo: '106', tipo: 'Eqüinos, asininos, muares', unidade: ['cabeça'] },
        { codigo: '107', tipo: 'Peixes extrativismo', unidade: ['kg'] },
        { codigo: '108', tipo: 'Ostras', unidade: ['dúzia'] },
        { codigo: '109', tipo: 'Peixes cultivo', unidade: ['kg'] },
        { codigo: '199', tipo: 'Outros animais', unidade: ['cabeça', 'unidade'] }
    ];

    readonly produtosProducaoAnimal = [
        { codigo: '111', tipo: 'Leite de bovinos', unidade: ['litro'] },
        { codigo: '113', tipo: 'Leite de caprinos', unidade: ['litro'] },
        { codigo: '114', tipo: 'Leite de ovinos', unidade: ['litro'] },
        { codigo: '201', tipo: 'Coalhada', unidade: ['kg'] },
        { codigo: '202', tipo: 'Creme de leite', unidade: ['kg'] },
        { codigo: '203', tipo: 'Doce de leite', unidade: ['kg'] },
        { codigo: '204', tipo: 'Manteiga', unidade: ['kg'] },
        { codigo: '205', tipo: 'Queijo ou requeijão', unidade: ['kg'] },
        { codigo: '206', tipo: 'Banha', unidade: ['kg'] },
        { codigo: '207', tipo: 'Carne verde de bovinos', unidade: ['kg'] },
        { codigo: '208', tipo: 'Carne verde de suínos', unidade: ['kg'] },
        { codigo: '209', tipo: 'Carne verde de caprinos', unidade: ['kg'] },
        { codigo: '210', tipo: 'Carne verde de ovinos', unidade: ['kg'] },
        { codigo: '211', tipo: 'Carne verde de outros animais', unidade: ['kg'] },
        { codigo: '212', tipo: 'Carne seca, carne de sol, carne tratada', unidade: ['kg'] },
        { codigo: '213', tipo: 'Embutidos (salame, linguiça etc.)', unidade: ['kg'] },
        { codigo: '214', tipo: 'Toucinho', unidade: ['kg'] },
        { codigo: '215', tipo: 'Couro e peles', unidade: ['kg'] },
        { codigo: '216', tipo: 'Ovos', unidade: ['dúzia'] },
        { codigo: '217', tipo: 'Mel', unidade: ['kg'] },
        { codigo: '218', tipo: 'Bebida láctea', unidade: ['litro'] },
        { codigo: '219', tipo: 'Filé de peixe', unidade: ['kg'] },
        { codigo: '220', tipo: 'Produtos processados da aquicultura', unidade: ['kg'] },
        { codigo: '299', tipo: 'Outros produtos', unidade: ['Dúzia', 'Grama (g)', 'Quilograma (kg)'] },
    ];

    readonly categoriaProducaoVegetal = ['Horticultura/olericultura', 'Lavouras permanentes', 'Lavouras temporárias – Produtos comuns', 'Lavouras temporárias – Forrageiras', 'Produtos beneficiados/transformados', 'Extração vegetal', 'Silvicultura'];

    readonly producaoVegetalExtrativismo = {
        'Horticultura/olericultura': [
            { codigo: '301', tipo: 'Abóbora (jerimum)', unidade: ['kg'] },
            { codigo: '302', tipo: 'Abobrinha', unidade: ['kg'] },
            { codigo: '303', tipo: 'Açafrão (cúrcuma)', unidade: ['kg'] },
            { codigo: '304', tipo: 'Acelga', unidade: ['kg'] },
            { codigo: '305', tipo: 'Agrião', unidade: ['kg'] },
            { codigo: '306', tipo: 'Aipo (salsão)', unidade: ['kg'] },
            { codigo: '307', tipo: 'Alcachofra', unidade: ['kg'] },
            { codigo: '308', tipo: 'Alface', unidade: ['pé'] },
            { codigo: '309', tipo: 'Alho poró', unidade: ['kg'] },
            { codigo: '310', tipo: 'Alho', unidade: ['kg'] },
            { codigo: '311', tipo: 'Almeirão', unidade: ['kg'] },
            { codigo: '312', tipo: 'Aspargo', unidade: ['kg'] },
            { codigo: '313', tipo: 'Azedinha', unidade: ['kg'] },
            { codigo: '314', tipo: 'Batata doce', unidade: ['kg'] },
            { codigo: '315', tipo: 'Batata inglesa', unidade: ['kg'] },
            { codigo: '316', tipo: 'Beringela', unidade: ['kg'] },
            { codigo: '317', tipo: 'Bertalha', unidade: ['kg'] },
            { codigo: '318', tipo: 'Beterraba', unidade: ['kg'] },
            { codigo: '319', tipo: 'Brócolis', unidade: ['molho'] },
            { codigo: '320', tipo: 'Bucha (esponja vegetal)', unidade: ['unidade'] },
            { codigo: '321', tipo: 'Caruru', unidade: ['kg'] },
            { codigo: '322', tipo: 'Cebola', unidade: ['kg'] },
            { codigo: '323', tipo: 'Cebolinha (folha)', unidade: ['molho'] },
            { codigo: '324', tipo: 'Cenoura', unidade: ['kg'] },
            { codigo: '325', tipo: 'Cheiro verde', unidade: ['molho'] },
            { codigo: '326', tipo: 'Chicória', unidade: ['molho'] },
            { codigo: '327', tipo: 'Chuchu', unidade: ['kg'] },
            { codigo: '328', tipo: 'Coentro', unidade: ['molho'] },
            { codigo: '329', tipo: 'Cogumelos comestíveis', unidade: ['kg'] },
            { codigo: '330', tipo: 'Couve manteiga', unidade: ['molho'] },
            { codigo: '331', tipo: 'Couve', unidade: ['molho'] },
            { codigo: '332', tipo: 'Couve flor', unidade: ['molho'] },
            { codigo: '333', tipo: 'Erva-doce (semente)', unidade: ['kg'] },
            { codigo: '334', tipo: 'Ervilha (vagem)', unidade: ['kg'] },
            { codigo: '335', tipo: 'Escarola', unidade: ['molho'] },
            { codigo: '336', tipo: 'Espinafre', unidade: ['kg'] },
            { codigo: '337', tipo: 'Flores', unidade: ['dúzia'] },
            { codigo: '338', tipo: 'Gengibre', unidade: ['kg'] },
            { codigo: '339', tipo: 'Hortelã', unidade: ['molho'] },
            { codigo: '340', tipo: 'Inhame', unidade: ['kg'] },
            { codigo: '341', tipo: 'Jiló', unidade: ['kg'] },
            { codigo: '342', tipo: 'Mandioquinha (batata-baroa)', unidade: ['kg'] },
            { codigo: '343', tipo: 'Manjerona', unidade: ['kg'] },
            { codigo: '344', tipo: 'Maxixe', unidade: ['kg'] },
            { codigo: '345', tipo: 'Melancia', unidade: ['kg'] },
            { codigo: '346', tipo: 'Melão', unidade: ['kg'] },
            { codigo: '347', tipo: 'Morango', unidade: ['kg'] },
            { codigo: '348', tipo: 'Mostarda', unidade: ['molho'] },
            { codigo: '349', tipo: 'Mudas vendidas para plantio', unidade: ['unidade'] },
            { codigo: '350', tipo: 'Nabiça', unidade: ['kg'] },
            { codigo: '351', tipo: 'Nabo', unidade: ['kg'] },
            { codigo: '352', tipo: 'Pepino', unidade: ['kg'] },
            { codigo: '353', tipo: 'Pimenta', unidade: ['kg'] },
            { codigo: '354', tipo: 'Pimentão', unidade: ['kg'] },
            { codigo: '355', tipo: 'Quiabo', unidade: ['kg'] },
            { codigo: '356', tipo: 'Rabanete', unidade: ['kg'] },
            { codigo: '357', tipo: 'Repolho', unidade: ['molho'] },
            { codigo: '358', tipo: 'Rúcula', unidade: ['molho'] },
            { codigo: '359', tipo: 'Salsa', unidade: ['molho'] },
            { codigo: '360', tipo: 'Sementes vendidas para plantio', unidade: ['kg'] },
            { codigo: '361', tipo: 'Taioba', unidade: ['kg'] },
            { codigo: '362', tipo: 'Vagem (feijão-vagem)', unidade: ['kg'] },
            { codigo: '399', tipo: 'Outros produtos', unidade: ['unidade', 'dúzia', 'cacho', 'Grama (g)', 'Quilograma (kg)', 'Saco de 40 kg', 'Saco de 50 kg', 'Saco de 60 kg'] },
        ],
        'Lavouras permanentes':[
            { codigo: '601', tipo: 'Abacate', unidade: ['fruto'] },
            { codigo: '602', tipo: 'Acerola', unidade: ['kg'] },
            { codigo: '603', tipo: 'Agave fibra', unidade: ['kg'] },
            { codigo: '604', tipo: 'Agave folha', unidade: ['kg'] },
            { codigo: '605', tipo: 'Algodão em caroço arbóreo', unidade: ['kg'] },
            { codigo: '606', tipo: 'Ameixa', unidade: ['fruto'] },
            { codigo: '607', tipo: 'Amora', unidade: ['folha', 'kg'] },
            { codigo: '608', tipo: 'Amora', unidade: ['fruto', 'kg'] },
            { codigo: '609', tipo: 'Azeitona', unidade: ['kg'] },
            { codigo: '610', tipo: 'Banana', unidade: ['Cacho'] },
            { codigo: '611', tipo: 'Bergamota (mexerica, tangerina)', unidade: ['fruto'] },
            { codigo: '612', tipo: 'Borracha líquida látex', unidade: ['kg'] },
            { codigo: '613', tipo: 'Borracha coagulada péla ou bola', unidade: ['kg'] },
            { codigo: '614', tipo: 'Cacau amêndoa', unidade: ['kg'] },
            { codigo: '615', tipo: 'Café em coco', unidade: ['kg'] },
            { codigo: '616', tipo: 'Cajá', unidade: ['fruto'] },
            { codigo: '617', tipo: 'Cajá manga', unidade: ['fruto'] },
            { codigo: '618', tipo: 'Caju castanha', unidade: ['kg'] },
            { codigo: '619', tipo: 'Caju pedúnculo', unidade: ['fruto'] },
            { codigo: '620', tipo: 'Canela casca', unidade: ['kg'] },
            { codigo: '621', tipo: 'Caqui', unidade: ['fruto'] },
            { codigo: '622', tipo: 'Carambola', unidade: ['fruto'] },
            { codigo: '623', tipo: 'Castanha européia', unidade: ['kg'] },
            { codigo: '624', tipo: 'Cerigüela ou Sirigüela', unidade: ['fruto'] },
            { codigo: '625', tipo: 'Chá-da-Índia', unidade: ['kg'] },
            { codigo: '626', tipo: 'Cidra', unidade: ['kg'] },
            { codigo: '627', tipo: 'Coco-da-Bahia', unidade: ['fruto'] },
            { codigo: '628', tipo: 'Cravo-da-Índia', unidade: ['	kg'] },
            { codigo: '629', tipo: 'Dendê (coco)', unidade: ['kg'] },
            { codigo: '630', tipo: 'Erva-mate', unidade: ['kg'] },
            { codigo: '631', tipo: 'Figo', unidade: ['fruto'] },
            { codigo: '632', tipo: 'Framboesa', unidade: ['kg'] },
            { codigo: '633', tipo: 'Fruta-de-conde', unidade: ['fruto'] },
            { codigo: '634', tipo: 'Goiaba', unidade: ['fruto'] },
            { codigo: '635', tipo: 'Graviola', unidade: ['fruto'] },
            { codigo: '636', tipo: 'Guaraná', unidade: ['kg'] },
            { codigo: '637', tipo: 'Jabuticaba', unidade: ['kg'] },
            { codigo: '638', tipo: 'Jaca', unidade: ['fruto'] },
            { codigo: '639', tipo: 'Jambo', unidade: ['fruto'] },
            { codigo: '640', tipo: 'Jamelão', unidade: ['kg'] },
            { codigo: '641', tipo: 'Jenipapo', unidade: ['fruto'] },
            { codigo: '642', tipo: 'Kiwi', unidade: ['fruto'] },
            { codigo: '643', tipo: 'Laranja', unidade: ['fruto'] },
            { codigo: '644', tipo: 'Lima', unidade: ['fruto'] },
            { codigo: '645', tipo: 'Limão', unidade: ['fruto'] },
            { codigo: '646', tipo: 'Louro (folha)', unidade: ['kg'] },
            { codigo: '647', tipo: 'Macadâmia', unidade: ['kg'] },
            { codigo: '648', tipo: 'Maçã', unidade: ['fruto'] },
            { codigo: '649', tipo: 'Mamão', unidade: ['fruto'] },
            { codigo: '650', tipo: 'Manga', unidade: ['fruto'] },
            { codigo: '651', tipo: 'Maracujá', unidade: ['fruto'] },
            { codigo: '652', tipo: 'Marmelo', unidade: ['fruto'] },
            { codigo: '653', tipo: 'Mexerica (bergamota, tangerina)', unidade: ['fruto'] },
            { codigo: '654', tipo: 'Nectarina', unidade: ['fruto'] },
            { codigo: '655', tipo: 'Nêspera', unidade: ['fruto'] },
            { codigo: '656', tipo: 'Noz (européia, pecã)', unidade: ['kg'] },
            { codigo: '657', tipo: 'Noz moscada', unidade: ['kg'] },
            { codigo: '658', tipo: 'Palmito', unidade: ['kg'] },
            { codigo: '659', tipo: 'Pêra', unidade: ['fruto'] },
            { codigo: '660', tipo: 'Pêssego', unidade: ['fruto'] },
            { codigo: '661', tipo: 'Pimenta do Reino', unidade: ['kg'] },
            { codigo: '662', tipo: 'Sapoti', unidade: ['fruto'] },
            { codigo: '663', tipo: 'Sisal (fibra)', unidade: ['kg'] },
            { codigo: '664', tipo: 'Sisal (folha)', unidade: ['kg'] },
            { codigo: '665', tipo: 'Tamarindo', unidade: ['kg'] },
            { codigo: '666', tipo: 'Tangerina (bergamota, mexerica)', unidade: ['fruto'] },
            { codigo: '667', tipo: 'Tungue', unidade: ['kg'] },
            { codigo: '668', tipo: 'Urucum', unidade: ['kg'] },
            { codigo: '669', tipo: 'Uva (para mesa)', unidade: ['kg'] },
            { codigo: '670', tipo: 'Uva (para vinho)', unidade: ['kg'] },
            { codigo: '671', tipo: 'Mudas de café', unidade: ['unidade'] },
            { codigo: '672', tipo: 'Mudas de cacau', unidade: ['unidade'] },
            { codigo: '673', tipo: 'Mudas de caju', unidade: ['unidade'] },
            { codigo: '674', tipo: 'Mudas de laranja', unidade: ['unidade'] },
            { codigo: '675', tipo: 'Mudas de maçã', unidade: ['unidade'] },
            { codigo: '676', tipo: 'Mudas de pêssego', unidade: ['unidade'] },
            { codigo: '677', tipo: 'Mudas de seringueira', unidade: ['unidade'] },
            { codigo: '678', tipo: 'Mudas de uva', unidade: ['unidade'] },
            { codigo: '679', tipo: 'Mudas de outras espécies', unidade: ['unidade'] },
            { codigo: '699', tipo: 'Outros produtos', unidade: ['unidade', 'dúzia', 'cacho', 'Grama (g)', 'Quilograma (kg)', 'Saco de 40 kg', 'Saco de 50 kg', 'Saco de 60 kg'] },
        ],
        'Lavouras temporárias – Produtos comuns':[
            { codigo: '701', tipo: 'Abacaxi', unidade: ['fruto'] },
            { codigo: '702', tipo: 'Abóbora  (jerimum, moranga)', unidade: ['fruto'] },
            { codigo: '703', tipo: 'Algodão em caroço (herbáceo)', unidade: ['kg'] },
            { codigo: '704', tipo: 'Alho', unidade: ['kg'] },
            { codigo: '705', tipo: 'Amendoim em casca (1a. Safra)', unidade: ['kg'] },
            { codigo: '706', tipo: 'Amendoim em casca (2a. Safra)', unidade: ['kg'] },
            { codigo: '707', tipo: 'Araruta', unidade: ['kg'] },
            { codigo: '708', tipo: 'Arroz em casca', unidade: ['kg'] },
            { codigo: '709', tipo: 'Aveia em casca', unidade: ['kg'] },
            { codigo: '710', tipo: 'Batata-doce', unidade: ['kg'] },
            { codigo: '711', tipo: 'Batata-inglesa (1a. Safra)', unidade: ['kg'] },
            { codigo: '712', tipo: 'Batata-inglesa (2a. Safra)', unidade: ['kg'] },
            { codigo: '713', tipo: 'Batata-inglesa (3a. Safra)', unidade: ['kg'] },
            { codigo: '714', tipo: 'Cana-de-açúcar', unidade: ['kg'] },
            { codigo: '715', tipo: 'Capim limão', unidade: ['kg'] },
            { codigo: '716', tipo: 'Cará', unidade: ['kg'] },
            { codigo: '717', tipo: 'Cebola', unidade: ['kg'] },
            { codigo: '718', tipo: 'Centeio em grão', unidade: ['kg'] },
            { codigo: '719', tipo: 'Cevada em casca', unidade: ['kg'] },
            { codigo: '720', tipo: 'Colza em grão', unidade: ['kg'] },
            { codigo: '721', tipo: 'Ervilha em grão', unidade: ['kg'] },
            { codigo: '722', tipo: 'Fava', unidade: ['kg'] },
            { codigo: '723', tipo: 'Feijão em grão', unidade: ['kg'] },
            { codigo: '726', tipo: 'Feijão verde', unidade: ['kg'] },
            { codigo: '727', tipo: 'Fumo em folha', unidade: ['kg'] },
            { codigo: '728', tipo: 'Gergelim', unidade: ['kg'] },
            { codigo: '729', tipo: 'Girassol (semente)', unidade: ['kg'] },
            { codigo: '730', tipo: 'Guandu', unidade: ['kg'] },
            { codigo: '731', tipo: 'Hortelã-pimente (menta)', unidade: ['kg'] },
            { codigo: '732', tipo: 'Inhame', unidade: ['kg'] },
            { codigo: '733', tipo: 'Jerimum (abóbora, moranga)', unidade: ['fruto'] },
            { codigo: '734', tipo: 'Juta (fibra)', unidade: ['kg'] },
            { codigo: '735', tipo: 'Juta (haste)', unidade: ['kg'] },
            { codigo: '736', tipo: 'Lentilha', unidade: ['kg'] },
            { codigo: '737', tipo: 'Linho (fibra)', unidade: ['kg'] },
            { codigo: '738', tipo: 'Linho (haste)', unidade: ['kg'] },
            { codigo: '739', tipo: 'Linho (semente)', unidade: ['kg'] },
            { codigo: '740', tipo: 'Malva (fibra)', unidade: ['kg'] },
            { codigo: '741', tipo: 'Malva (haste)', unidade: ['kg'] },
            { codigo: '742', tipo: 'Mamona', unidade: ['kg'] },
            { codigo: '743', tipo: 'Mandioca', unidade: ['kg'] },
            { codigo: '744', tipo: 'Macaxeira (aipim)', unidade: ['kg'] },
            { codigo: '745', tipo: 'Melancia', unidade: ['kg'] },
            { codigo: '746', tipo: 'Melão', unidade: ['kg'] },
            { codigo: '747', tipo: 'Menta (hortelã, pimenta)', unidade: ['kg'] },
            { codigo: '748', tipo: 'Milho em grão', unidade: ['kg'] },
            { codigo: '749', tipo: 'Milho em espiga (verde)', unidade: ['kg'] },
            { codigo: '750', tipo: 'Moranga (abóbora)', unidade: ['fruto'] },
            { codigo: '751', tipo: 'Morango', unidade: ['kg'] },
            { codigo: '752', tipo: 'Mudas vendidas para plantio', unidade: ['unidade'] },
            { codigo: '753', tipo: 'Rami caule', unidade: ['kg'] },
            { codigo: '754', tipo: 'Rami fibra', unidade: ['kg'] },
            { codigo: '755', tipo: 'Soja em grão', unidade: ['kg'] },
            { codigo: '756', tipo: 'Sorgo em grão', unidade: ['kg'] },
            { codigo: '757', tipo: 'Sorgo vassoura', unidade: ['kg'] },
            { codigo: '758', tipo: 'Tomate', unidade: ['kg'] },
            { codigo: '759', tipo: 'Tremoço', unidade: ['kg'] },
            { codigo: '760', tipo: 'Trigo em grão', unidade: ['kg'] },
            { codigo: '761', tipo: 'Trigo preto (mourisco, sarraceno)', unidade: ['kg'] },
        ],
        'Lavouras temporárias – Forrageiras':[
            { codigo: '762', tipo: 'Alfafa forrageira', unidade: ['kg'] },
            { codigo: '763', tipo: 'Azevém', unidade: ['kg'] },
            { codigo: '764', tipo: 'Capim-elefante-napier', unidade: ['kg'] },
            { codigo: '765', tipo: 'Cana forrageira', unidade: ['kg'] },
            { codigo: '766', tipo: 'Milho forrageiro', unidade: ['kg'] },
            { codigo: '767', tipo: 'Palma forrageira', unidade: ['kg'] },
            { codigo: '768', tipo: 'Sorgo forrageiro', unidade: ['kg'] },
            { codigo: '769', tipo: 'Outras forrageiras - capins e leguminosa', unidade: ['kg'] },
            { codigo: '799', tipo: 'Outros produtos', unidade: ['unidade', 'dúzia', 'cacho', 'Grama (g)', 'Quilograma (kg)', 'Saco de 40 kg', 'Saco de 50 kg', 'Saco de 60 kg'] },
        ],
        'Produtos beneficiados/transformados':[
            { codigo: '801', tipo: 'Xarope ou vinho de açaí', unidade: ['litro'] },
            { codigo: '802', tipo: 'Arroz beneficiado em grão', unidade: ['kg'] },
            { codigo: '803', tipo: 'Fubá de babaçu', unidade: ['kg'] },
            { codigo: '804', tipo: 'Óleo de babaçu', unidade: ['litro'] },
            { codigo: '805', tipo: 'Café em grão', unidade: ['kg'] },
            { codigo: '806', tipo: 'Açúcar', unidade: ['kg'] },
            { codigo: '807', tipo: 'Aguardente de cana', unidade: ['litro'] },
            { codigo: '808', tipo: 'Álcool de cana', unidade: ['litro'] },
            { codigo: '809', tipo: 'Garapa ou caldo de cana', unidade: ['litro'] },
            { codigo: '810', tipo: 'Melado', unidade: ['litro'] },
            { codigo: '811', tipo: 'Rapadura', unidade: ['kg'] },
            { codigo: '812', tipo: 'Vinagre de cana', unidade: ['litro'] },
            { codigo: '813', tipo: 'Óleo de capim-limão', unidade: ['litro'] },
            { codigo: '814', tipo: 'Azeite-de-dendê', unidade: ['litro'] },
            { codigo: '815', tipo: 'Óleo de dendê', unidade: ['litro'] },
            { codigo: '816', tipo: 'Aguardente de frutas', unidade: ['litro'] },
            { codigo: '817', tipo: 'Compotas de frutas', unidade: ['kg'] },
            { codigo: '818', tipo: 'Frutas cristalizadas', unidade: ['kg'] },
            { codigo: '819', tipo: 'Geléia de frutas', unidade: ['kg'] },
            { codigo: '820', tipo: 'Licor de frutas', unidade: ['litro'] },
            { codigo: '821', tipo: 'Pasta de frutas', unidade: ['kg'] },
            { codigo: '822', tipo: 'Vinho de frutas', unidade: ['litro'] },
            { codigo: '823', tipo: 'Fumo em rolo ou corda', unidade: ['kg'] },
            { codigo: '824', tipo: 'Apara ou lkasca de mandioca', unidade: ['kg'] },
            { codigo: '825', tipo: 'Carimã amido azedo de mandioca', unidade: ['kg'] },
            { codigo: '826', tipo: 'Farinha de mandioca', unidade: ['kg'] },
            { codigo: '827', tipo: 'Goma polvilho de mandioca', unidade: ['kg'] },
            { codigo: '828', tipo: 'Massa puba de mandioca', unidade: ['kg'] },
            { codigo: '829', tipo: 'Tapioca beiju de mandioca', unidade: ['kg'] },
            { codigo: '830', tipo: 'Tiquira aguardente de mandioca', unidade: ['litro'] },
            { codigo: '831', tipo: 'Óleo de menta', unidade: ['litro'] },
            { codigo: '832', tipo: 'Canjica de milho', unidade: ['kg'] },
            { codigo: '833', tipo: 'Canjiquinha de milho', unidade: ['kg'] },
            { codigo: '834', tipo: 'Fubá de milho', unidade: ['kg'] },
            { codigo: '835', tipo: 'Fubarina de milho', unidade: ['kg'] },
            { codigo: '836', tipo: 'Essência, óleo de pau-rosa', unidade: ['litro'] },
            { codigo: '837', tipo: 'Aguardente de uva', unidade: ['litro'] },
            { codigo: '838', tipo: 'Suco de uva', unidade: ['litro'] },
            { codigo: '839', tipo: 'Vinho de uva', unidade: ['litro'] },
            { codigo: '840', tipo: 'Vinagre de uva', unidade: ['litro'] },
            { codigo: '899', tipo: 'Outros produtos', unidade: ['Unidade', 'Dúzia', 'Cacho', 'Grama (g)', 'Quilograma (kg)', 'Saco de 40 kg', 'Saco de 50 kg', 'Saco de 60 kg', 'Mililitro (ml)', 'Litro (l)', 'Metro cúbico (m³)'] },
        ],
        'Extração vegetal':[
            { codigo: '401', tipo: 'Abiu', unidade: ['fruto'] },
            { codigo: '402', tipo: 'Abricó', unidade: ['fruto'] },
            { codigo: '403', tipo: 'Açaí (fruto)', unidade: ['kg'] },
            { codigo: '404', tipo: 'Açaí (palmito)', unidade: ['kg'] },
            { codigo: '405', tipo: 'Andiroba (semente)', unidade: ['kg'] },
            { codigo: '406', tipo: 'Angico com casca', unidade: ['kg'] },
            { codigo: '407', tipo: 'Babaçu coco', unidade: ['kg'] },
            { codigo: '408', tipo: 'Babaçu (amêndoa)', unidade: ['kg'] },
            { codigo: '409', tipo: 'Bacabá (caroço)', unidade: ['kg'] },
            { codigo: '410', tipo: 'Bacuri', unidade: ['fruto'] },
            { codigo: '411', tipo: 'Balaca (goma não elástica)', unidade: ['kg'] },
            { codigo: '412', tipo: 'Bambu (taquara)', unidade: ['m³'] },
            { codigo: '413', tipo: 'Borracha líquida', unidade: ['kg'] },
            { codigo: '414', tipo: 'Borracha coagulada', unidade: ['kg'] },
            { codigo: '415', tipo: 'Buriti (coco)', unidade: ['kg'] },
            { codigo: '416', tipo: 'Buriti (palha)', unidade: ['kg'] },
            { codigo: '417', tipo: 'Butiá (coco)', unidade: ['kg'] },
            { codigo: '418', tipo: 'Butiá (fibra)', unidade: ['kg'] },
            { codigo: '419', tipo: 'Cajarana', unidade: ['unidade'] },
            { codigo: '420', tipo: 'Caju (castanha)', unidade: ['kg'] },
            { codigo: '421', tipo: 'Caju (pedúnculo)', unidade: ['fruto'] },
            { codigo: '422', tipo: 'Cambucá', unidade: ['fruto'] },
            { codigo: '423', tipo: 'Carnaúba (cêra)', unidade: ['kg'] },
            { codigo: '424', tipo: 'Carnaúba (palha)', unidade: ['kg'] },
            { codigo: '425', tipo: 'Carnaúba (pó de palha)', unidade: ['kg'] },
            { codigo: '426', tipo: 'Carnaúba (olho de palha)', unidade: ['kg'] },
            { codigo: '427', tipo: 'Caroá (fibra)', unidade: ['kg'] },
            { codigo: '428', tipo: 'Carvão vegetal', unidade: ['kg'] },
            { codigo: '429', tipo: 'Cascas taníferas', unidade: ['kg'] },
            { codigo: '430', tipo: 'Castanha-do-Pará', unidade: ['kg'] },
            { codigo: '431', tipo: 'Calcho (goma elástica)', unidade: ['kg'] },
            { codigo: '432', tipo: 'Cipó-timbó ou timbó', unidade: ['unidade'] },
            { codigo: '433', tipo: 'Copaiba (oléo)', unidade: ['kg'] },
            { codigo: '434', tipo: 'Coquirama (goma não elástica)', unidade: ['kg'] },
            { codigo: '435', tipo: 'Cumaru (semente)', unidade: ['kg'] },
            { codigo: '436', tipo: 'Cupuaçu', unidade: ['fruto'] },
            { codigo: '437', tipo: 'Dormentes', unidade: ['unidade'] },
            { codigo: '438', tipo: 'Erva-mate', unidade: ['kg'] },
            { codigo: '439', tipo: 'Estacas de madeira', unidade: ['unidade'] },
            { codigo: '440', tipo: 'Fruta-pão', unidade: ['fruto'] },
            { codigo: '441', tipo: 'Imbu ou Umbu', unidade: ['unidade'] },
            { codigo: '442', tipo: 'Ipecacuanha ou Poaia', unidade: ['unidade'] },
            { codigo: '443', tipo: 'Jaborandi folha', unidade: ['unidade'] },
            { codigo: '444', tipo: 'Jatobá e jataí', unidade: ['unidade'] },
            { codigo: '445', tipo: 'Jenipapo', unidade: ['unidade'] },
            { codigo: '446', tipo: 'Lenha', unidade: ['m³'] },
            { codigo: '447', tipo: 'Licure (coquilho)', unidade: ['kg'] },
            { codigo: '448', tipo: 'Licure (cêra)', unidade: ['kg'] },
            { codigo: '449', tipo: 'Licure (folha)', unidade: ['kg'] },
            { codigo: '450', tipo: 'Maçaranduba (goma não elástica)', unidade: ['kg'] },
            { codigo: '451', tipo: 'Macaúba (semente)', unidade: ['kg'] },
            { codigo: '452', tipo: 'Madeiras em toras', unidade: ['m³'] },
            { codigo: '453', tipo: 'Madeira para papel', unidade: ['m³'] },
            { codigo: '454', tipo: 'Malva (fibra)', unidade: ['kg'] },
            { codigo: '455', tipo: 'Malva (haste)', unidade: ['kg'] },
            { codigo: '456', tipo: 'Mangabeira (goma elástica)', unidade: ['kg'] },
            { codigo: '457', tipo: 'Mangaba (fruto)', unidade: ['kg'] },
            { codigo: '458', tipo: 'Mançoba (goma elástica)', unidade: ['kg'] },
            { codigo: '459', tipo: 'Moirões de madeira', unidade: ['unidade'] },
            { codigo: '460', tipo: 'Murci', unidade: ['kg'] },
            { codigo: '461', tipo: 'Murumuru (semente)', unidade: ['kg'] },
            { codigo: '462', tipo: 'Oiti', unidade: ['fruto'] },
            { codigo: '463', tipo: 'Oiticica (semente)', unidade: ['kg'] },
            { codigo: '464', tipo: 'Ouricuri (coco)', unidade: ['kg'] },
            { codigo: '465', tipo: 'Outras fibras', unidade: ['kg'] },
            { codigo: '466', tipo: 'Painas', unidade: ['kg'] },
            { codigo: '467', tipo: 'Palanque ou palanca', unidade: ['unidade'] },
            { codigo: '468', tipo: 'Palmito ou guariroba', unidade: ['kg'] },
            { codigo: '469', tipo: 'Pequi (coco)', unidade: ['kg'] },
            { codigo: '470', tipo: 'Piaçaba coquilho', unidade: ['kg'] },
            { codigo: '471', tipo: 'Piaçaba fibra', unidade: ['kg'] },
            { codigo: '472', tipo: 'Pinhão', unidade: ['kg'] },
            { codigo: '473', tipo: 'Pitomba', unidade: ['kg'] },
            { codigo: '474', tipo: 'Postes de madeira', unidade: ['unidade'] },
            { codigo: '475', tipo: 'Pupunha', unidade: ['kg'] },
            { codigo: '476', tipo: 'Resinas óleos e graxas vegetais', unidade: ['kg'] },
            { codigo: '477', tipo: 'Sagu fécula', unidade: ['kg'] },
            { codigo: '478', tipo: 'Seringa látex', unidade: ['unidade'] },
            { codigo: '479', tipo: 'Seringa péla ou bola', unidade: ['unidade'] },
            { codigo: '480', tipo: 'Sorva (goma não elástica)', unidade: ['kg'] },
            { codigo: '481', tipo: 'Taperebá cajarana', unidade: ['kg'] },
            { codigo: '482', tipo: 'Timbó ou cipó-timbó', unidade: ['kg'] },
            { codigo: '483', tipo: 'Tucun (coco)', unidade: ['kg'] },
            { codigo: '484', tipo: 'Tucun (fibra)', unidade: ['kg'] },
            { codigo: '485', tipo: 'Ucuuba (amêndoa)', unidade: ['kg'] },
            { codigo: '486', tipo: 'Umbu ou Imbu', unidade: ['kg'] },
            { codigo: '487', tipo: 'Vigas', unidade: ['unidade'] },
            { codigo: '499', tipo: 'Outros produtos', unidade: ['Unidade', 'Dúzia', 'Cacho', 'Grama (g)', 'Quilograma (kg)', 'Saco de 40 kg', 'Saco de 50 kg', 'Saco de 60 kg', 'Mililitro (ml)', 'Litro (l)', 'Metro cúbico (m³)'] },
        ],
        'Silvicultura':[
            { codigo: '501', tipo: 'Casca de acácia negra', unidade: ['kg'] },
            { codigo: '502', tipo: 'Carvão vegetal', unidade: ['kg'] },
            { codigo: '503', tipo: 'Dormentes', unidade: ['unidade'] },
            { codigo: '504', tipo: 'Estacas', unidade: ['unidade'] },
            { codigo: '505', tipo: 'Folhas de eucalipto', unidade: ['kg'] },
            { codigo: '506', tipo: 'Lenha', unidade: ['m³'] },
            { codigo: '507', tipo: 'Madeira em toras', unidade: ['m³'] },
            { codigo: '508', tipo: 'Madeira para papel', unidade: ['m³'] },
            { codigo: '509', tipo: 'Moirões', unidade: ['unidade'] },
            { codigo: '510', tipo: 'Palanque ou palanca', unidade: ['unidade'] },
            { codigo: '511', tipo: 'Postes', unidade: ['unidade'] },
            { codigo: '512', tipo: 'Resinas óleos e graxas vegetais', unidade: ['kg'] },
            { codigo: '513', tipo: 'Sementes vendidas para plantio', unidade: ['kg'] },
            { codigo: '514', tipo: 'Vagem de algaroba', unidade: ['kg'] },
            { codigo: '515', tipo: 'Vigas', unidade: ['unidade'] },
            { codigo: '516', tipo: 'Mudas de eucalipto', unidade: ['unidade'] },
            { codigo: '517', tipo: 'Mudas de pinheiro brasileiro', unidade: ['unidade'] },
            { codigo: '518', tipo: 'Mudas de pinus americano', unidade: ['unidade'] },
            { codigo: '519', tipo: 'Mudas de algaroba', unidade: ['unidade'] },
            { codigo: '520', tipo: 'Mudas de acácia-negra', unidade: ['unidade'] },
            { codigo: '521', tipo: 'Mudas de outras espécies', unidade: ['unidade'] },
            { codigo: '599', tipo: 'Outros produtos', unidade: ['Unidade', 'Dúzia', 'Cacho', 'Grama (g)', 'Quilograma (kg)', 'Saco de 40 kg', 'Saco de 50 kg', 'Saco de 60 kg', 'Mililitro (ml)', 'Litro (l)', 'Metro cúbico (m³)'] },
        ]
    };
}
