name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Configurar o Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Cache de dependências do pip
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Instalar dependências
      - run: pip install mkdocs-material pillow cairosvg

      # Validar configuração do MkDocs para capturar possiveis erros antes do deploy
      - run: mkdocs build --strict

      # Deploy para o GitHub Pages
      - run: mkdocs gh-deploy --force --remote-branch gh-pages
